# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99028cf5cbcaccf5d85ec893eee3da33806737b8ca3c77c12d17ca71554772db7f64775ebfbc6389f0ad1fc4dbce47f320e018d806850e3227bd8eed2c5fb7c6

test:
  secret_key_base: 87c8b2b92ae9a669538dcb49f9377f22e8e7df58f3bd008fd6a2cc608b749ef13383452552cac3a307570de65204fad53c15301910292ead3d4c5e200171421d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
